//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewTechologyEntities : DbContext
    {
        public NewTechologyEntities()
            : base("name=NewTechologyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ЕденицыИзмерения> ЕденицыИзмерения { get; set; }
        public virtual DbSet<ЗаявкиПартнеров> ЗаявкиПартнеров { get; set; }
        public virtual DbSet<Материалы> Материалы { get; set; }
        public virtual DbSet<Партнеры> Партнеры { get; set; }
        public virtual DbSet<Продукция> Продукция { get; set; }
        public virtual DbSet<СоставЗаявки> СоставЗаявки { get; set; }
        public virtual DbSet<СоставПродукции> СоставПродукции { get; set; }
        public virtual DbSet<ТипыМатериалов> ТипыМатериалов { get; set; }
        public virtual DbSet<ТипыПартнеров> ТипыПартнеров { get; set; }
        public virtual DbSet<ТипыПродукции> ТипыПродукции { get; set; }
    }
}
