//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаявкиПартнеров
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЗаявкиПартнеров()
        {
            this.СоставЗаявки = new HashSet<СоставЗаявки>();
        }
    
        public int Код_Заявки { get; set; }
        public int Код_Партнера { get; set; }
    
        public virtual Партнеры Партнеры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаявки> СоставЗаявки { get; set; }
    }
}
