//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материалы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материалы()
        {
            this.СоставПродукции = new HashSet<СоставПродукции>();
        }
    
        public int Код_Материала { get; set; }
        public int Код_ТипаМатериала { get; set; }
        public string Наименование { get; set; }
        public int Код_ЕдиницыИзмерения { get; set; }
        public decimal Стоимость { get; set; }
        public int КоличествоНаСкладе { get; set; }
    
        public virtual ЕденицыИзмерения ЕденицыИзмерения { get; set; }
        public virtual ТипыМатериалов ТипыМатериалов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПродукции> СоставПродукции { get; set; }
    }
}
