//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партнеры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Партнеры()
        {
            this.ЗаявкиПартнеров = new HashSet<ЗаявкиПартнеров>();
        }
    
        public int Код_Партнера { get; set; }
        public int Код_ТипаПартнера { get; set; }
        public string Наименование { get; set; }
        public string Директор { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public string Телефон { get; set; }
        public string ЮридическийАдрес { get; set; }
        public string ИНН { get; set; }
        public int Рейтинг { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаявкиПартнеров> ЗаявкиПартнеров { get; set; }
        public virtual ТипыПартнеров ТипыПартнеров { get; set; }
    }
}
