//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTechn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.СоставЗаявки = new HashSet<СоставЗаявки>();
            this.СоставПродукции = new HashSet<СоставПродукции>();
        }
    
        public int Код_Продукции { get; set; }
        public int Код_ТипаПродукции { get; set; }
        public string НаименованиеПродукции { get; set; }
        public int Артикул { get; set; }
        public decimal МинимальнаяСтоимостьДляПартнера { get; set; }
    
        public virtual ТипыПродукции ТипыПродукции { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаявки> СоставЗаявки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПродукции> СоставПродукции { get; set; }
    }
}
